//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atelier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id_order { get; set; }
        public int Id_client { get; set; }
        public int Id_product { get; set; }
        public int Id_material { get; set; }
        public int Id_worker { get; set; }
        public int Id_size { get; set; }
        public System.DateTime Date_order { get; set; }
        public decimal Price { get; set; }
        public string Order_status { get; set; }
        public string Size_Number { get; set; }
        public Nullable<decimal> Chest_girth { get; set; }
        public Nullable<decimal> Waist_girth { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Materials Materials { get; set; }
        public virtual Products Products { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
