//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atelier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int Id_product { get; set; }
        public string Name_product { get; set; }
        public string Example_product { get; set; }
    
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
