//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atelier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sizes
    {
        public int Id_size { get; set; }
        public string Size_Number { get; set; }
        public decimal Chest_girth { get; set; }
        public decimal Waist_girth { get; set; }
    }
}
